# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Zeal' do
pod 'Charts', '2.1.6'
pod 'MLVerticalProgressView'
pod 'BEMCheckBox', '1.1.1'
pod 'TextFieldEffects'


end

target 'ZealTests' do

end

target 'ZealUITests' do

end

